class CreatePlans < ActiveRecord::Migration
  def self.up
    Plan.create(:name => "Free",
                :invoices => 3,
                :users => 5,
                :clients => 10,
                :allow_custom_css => false,
                :unbranded_emails => false,
                :print_css => true,
                :draft_invoices => false,
                :invoice_templates => true,
                :cost_for_za => 0,
                :display_cost_for_za => "Free",
                :display_currency_cost_for_za => "Free",
                :cost_for_com => 0,
                :display_cost_for_com => "Free",
                :display_currency_cost_for_com => "Free",
                :cost_for_uk => 0,
                :display_cost_for_uk => "Free",
                :display_currency_cost_for_uk => "Free",
                :seq => 1)

    Plan.create(:name => "Lite",
                :invoices => 30,
                :users => 20,
                :clients => 100,
                :allow_custom_css => true,
                :unbranded_emails => true,
                :print_css => true,
                :draft_invoices => true,
                :invoice_templates => true,
                :cost_for_za => 45,
                :display_cost_for_za => "R45",
                :display_currency_cost_for_za => "ZAR45",
                :cost_for_com => 7,
                :display_cost_for_com => "$7",
                :display_currency_cost_for_com => "USD7",
                :cost_for_uk => 4,
                :display_cost_for_uk => "£4",
                :display_currency_cost_for_uk => "GBP4",
                :seq => 2)

    Plan.create(:name => "Hardcore",
                :invoices => 200,
                :users => 100,
                :clients => 0,
                :allow_custom_css => true,
                :unbranded_emails => true,
                :print_css => true,
                :draft_invoices => true,
                :invoice_templates => true,
                :cost_for_za => 100,
                :display_cost_for_za => "R100",
                :display_currency_cost_for_za => "ZAR100",
                :cost_for_com => 15,
                :display_cost_for_com => "$15",
                :display_currency_cost_for_com => "USD15",
                :cost_for_uk => 8,
                :display_cost_for_uk => "£8",
                :display_currency_cost_for_uk => "GBP8",
                :seq => 3)

    Plan.create(:name => "Ultimate",
                :invoices => 200,
                :users => 1000,
                :clients => 0,
                :allow_custom_css => true,
                :unbranded_emails => true,
                :print_css => true,
                :draft_invoices => true,
                :invoice_templates => true,
                :cost_for_za => 250,
                :display_cost_for_za => "R250",
                :display_currency_cost_for_za => "ZAR250",
                :cost_for_com => 40,
                :display_cost_for_com => "$40",
                :display_currency_cost_for_com => "USD40",
                :cost_for_uk => 20,
                :display_cost_for_uk => "£20",
                :display_currency_cost_for_uk => "GBP20",
                :seq => 4)

    Plan.create(:name => "Friends",
                :special => true,
                :invoices => 20,
                :users => 1,
                :clients => 20,
                :allow_custom_css => false,
                :unbranded_emails => false,
                :print_css => true,
                :draft_invoices => false,
                :invoice_templates => true,
                :cost_for_za => 0,
                :display_cost_for_za => "Free",
                :display_currency_cost_for_za => "Free",
                :cost_for_com => 0,
                :display_cost_for_com => "Free",
                :display_currency_cost_for_com => "Free",
                :cost_for_uk => 0,
                :display_cost_for_uk => "Free",
                :display_currency_cost_for_uk => "Free",
                :seq => 5)
  end

  def self.down
      Plan.delete_all
  end
end
